The httpclient dependency included is of version 4.0.2, 			        which is incompatible with the version of httpclient pulled in 			        by Xebium in the webapp-example project, which is 4.1.2. 			        The result is a hidden 			        NoClassDefFoundError: org/apache/http/conn/scheme/SchemeSocketFactory 			        which causes Firefox to silently fail to boot from Selenium 			        and hence no Xebium based tests get run under the RunTestsMojo. 			        Ultimately we probably need to implement a custom-scoped 			        org.codehaus.plexus.classworlds.realm.ClassRealm 			        with which to boot FitNesse, but this is difficult as 			        the threads it launches are without any public access or interface, 			        meaning a custom FitNesseMain class might need to be written. 			        This may be desirable anyway, as we also have trouble identifying 			        the FitNesse thread to join in WikiMojo. 			        For now, as reporting functionality is not yet implemented, 			        an exclusion will do! 			        http://maven.apache.org/guides/mini/guide-maven-classloading.html